name: Validate PR
on:
  push:
    branches: [ main ]
jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v4
      - run: |
          dotnet tool restore
          dotnet csharpier .
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated CSharpier Formatting
